In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# square root of each number
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
# exponent value of each number
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)

A

array([-0.00562827,  0.8442982 , -0.84224393,  0.61449375, -0.21156565,
       -1.13541478,  0.78873532,  2.31019959, -0.30341975, -1.9185044 ])

In [6]:
B = np.random.randn(10)
B

array([ 0.50569221, -0.28208701,  0.05587302,  1.39862988, -0.60598724,
        0.46098161, -0.07198107,  1.25194951, -0.66097488, -0.54938306])

In [7]:
# Binary Functions
np.add(A,B) # sum of each index together

array([ 0.50006394,  0.56221118, -0.78637091,  2.01312362, -0.81755289,
       -0.67443317,  0.71675424,  3.5621491 , -0.96439463, -2.46788747])

In [8]:
np.maximum(A,B) # maximum of each index

array([ 0.50569221,  0.8442982 ,  0.05587302,  1.39862988, -0.21156565,
        0.46098161,  0.78873532,  2.31019959, -0.30341975, -0.54938306])

In [9]:
# Open Webside
website = 'https://docs.cupy.dev/en/stable/reference/ufunc.html'
import webbrowser
webbrowser.open(website)

True