In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 = Series([0,1,2], index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [15]:
dframe1

X         Y         Z
0 -0.748967  0.256864  0.388334
1 -1.365933  0.235140 -0.400838
2  0.661176 -1.506134  0.569276
3  1.397598 -2.106565  0.914047

In [16]:
dframe2

Y         Q         X
0  0.635141  0.428111  0.324831
1  0.256538  0.279165  0.065128
2 -0.343816 -0.559271 -0.946616

In [17]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.748967  0.256864  0.388334       NaN
1 -1.365933  0.235140 -0.400838       NaN
2  0.661176 -1.506134  0.569276       NaN
3  1.397598 -2.106565  0.914047       NaN
0  0.324831  0.635141       NaN  0.428111
1  0.065128  0.256538       NaN  0.279165
2 -0.946616 -0.343816       NaN -0.559271

In [18]:
pd.concat([dframe1, dframe2], ignore_index=True)

X         Y         Z         Q
0 -0.748967  0.256864  0.388334       NaN
1 -1.365933  0.235140 -0.400838       NaN
2  0.661176 -1.506134  0.569276       NaN
3  1.397598 -2.106565  0.914047       NaN
4  0.324831  0.635141       NaN  0.428111
5  0.065128  0.256538       NaN  0.279165
6 -0.946616 -0.343816       NaN -0.559271

In [ ]:
url = 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html'